In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))
%matplotlib inline

In [3]:
def get_peak_hist(df, exp=None):
    if exp is None:
        mask = np.ones(len(df), dtype=bool)
    else:
        mask = df.experiment==exp
    return np.histogram(df[mask].Z, bins=np.linspace(10,305,30))[0]

In [4]:
def print_stats(df):
    print("{} different experiments".format(len(set(df.experiment))))
    print("{} detected neurons in total".format(len(df)))
    print("{:.2f} neurons per experiment on average".format(len(df)/len(set(df.experiment))))
    
    print("")
    exps = set(df.experiment)
    divs = []
    for exp in exps:
        div = exp[exp.lower().find("div"):exp.lower().find("div")+5]
        if div not in divs:
            divs.append(div)
            
    for d in np.sort(divs):
        nexp = len([exp for exp in exps if d in exp])
        nneur = len(df[df['experiment'].str.contains(d)])
        print("{}:".format(d))
        print("{} experiments\n{} neurons\n{:.2f} neurons per exp\n".format(nexp, nneur, nneur/nexp))

In [5]:
# base_directory = '/Volumes/LaCie/LaCie/Gcampf6/'

# gaers = pd.DataFrame()
# wistar = pd.DataFrame()

# for dirpath, dirnames, filenames in os.walk(base_directory):
#     for filename in [f for f in filenames if f.endswith(".csv")]:
#         file_path = os.path.join(dirpath, filename)
#         df = pd.read_csv(file_path)
#         df['experiment'] = filename.split('.')[0]
#         if 'gaers' in filename.lower():
#             gaers = gaers.append(df)
#         elif 'wistar' in filename.lower():
#             wistar = wistar.append(df)
#         else:
#             print(filename)

In [206]:
# gaers.to_csv('/Users/thomasvuillaume/Work/Dev/neuronDetector/results/gaers20180805.csv')
# wistar.to_csv('/Users/thomasvuillaume/Work/Dev/neuronDetector/results/wistar20180805.csv')

In [6]:
gaers = pd.read_csv('results/gaers20180805.csv')
wistar = pd.read_csv('results/wistar20180805.csv')

In [7]:
gaers.describe()

,Unnamed: 0,Volume (pixel^3),Surface (pixel^2),Nb of obj. voxels,Nb of surf. voxels,IntDen,Mean,StdDev,Median,Min,...,Median dist. to surf. (pixel),XM,YM,ZM,BX,BY,BZ,B-width,B-height,B-depth
count,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,1.250000e+04,12500.0,12500.0,12500.0,12500.0,...,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000
mean,95.029600,2041.437280,1936.505600,2041.437280,1061.651120,5.205665e+05,255.0,0.0,255.0,255.0,...,10.544605,458.962725,586.073552,122.639071,445.415840,571.876560,115.043440,28.528000,29.321600,18.304720
std,75.179009,1971.044546,1458.912106,1971.044546,811.269277,5.026164e+05,0.0,0.0,0.0,0.0,...,5.679325,289.333563,279.797329,88.477370,288.917904,280.976289,91.204354,22.485019,23.668665,24.292515
min,0.000000,400.000000,400.000000,400.000000,191.000000,1.020000e+05,255.0,0.0,255.0,255.0,...,4.203000,0.492000,0.877000,1.125000,0.000000,0.000000,1.000000,3.000000,3.000000,1.000000
25%,38.000000,685.750000,964.000000,685.750000,501.000000,1.748662e+05,255.0,0.0,255.0,255.0,...,7.134750,204.784250,354.068250,39.050000,189.000000,336.000000,26.000000,16.000000,16.000000,5.000000
50%,79.000000,1263.000000,1445.000000,1263.000000,793.000000,3.220650e+05,255.0,0.0,255.0,255.0,...,8.966500,444.183000,600.253000,110.314000,429.000000,587.000000,105.000000,23.000000,24.000000,9.000000
75%,132.000000,2605.250000,2386.000000,2605.250000,1343.000000,6.643388e+05,255.0,0.0,255.0,255.0,...,11.965000,702.055750,829.013500,193.999500,687.000000,817.000000,190.000000,33.000000,35.000000,18.000000
max,434.000000,9998.000000,13106.000000,9998.000000,7126.000000,2.549490e+06,255.0,0.0,255.0,255.0,...,76.760000,1022.538000,1022.505000,294.998000,1021.000000,1021.000000,295.000000,332.000000,397.000000,295.000000

In [20]:
gaers.sort_values('Volume (pixel^3)').tail()

,Unnamed: 0,Volume (pixel^3),Surface (pixel^2),Nb of obj. voxels,Nb of surf. voxels,IntDen,Mean,StdDev,Median,Min,...,XM,YM,ZM,BX,BY,BZ,B-width,B-height,B-depth,experiment
1852,119,9990,6646,9990,3806,2547450,255,0,255,255,...,67.024,215.021,62.760,60,163,43,19,79,40,2GAERSDIV4_3_2
1584,119,9990,6646,9990,3806,2547450,255,0,255,255,...,67.024,215.021,62.760,60,163,43,19,79,40,2GAERSDIV4_3_1
1225,74,9995,6278,9995,3423,2548725,255,0,255,255,...,24.251,715.433,105.819,12,696,92,38,68,47,2GAERSDIV4_1_6
7857,17,9997,6416,9997,3756,2549235,255,0,255,255,...,64.907,924.298,79.976,38,868,76,44,91,13,GAERSDIV14_3_2
11074,68,9998,5446,9998,3078,2549490,255,0,255,255,...,786.403,88.147,151.010,774,76,136,26,25,32,GAERSDIV4_2_3?

In [29]:
gaers.iloc[11074]

Unnamed: 0                                   68
Volume (pixel^3)                           9998
Surface (pixel^2)                          5446
Nb of obj. voxels                          9998
Nb of surf. voxels                         3078
IntDen                                  2549490
Mean                                        255
StdDev                                        0
Median                                      255
Min                                         255
Max                                         255
X                                        786.35
Y                                        88.148
Z                                       151.011
Mean dist. to surf. (pixel)              13.155
SD dist. to surf. (pixel)                 2.342
Median dist. to surf. (pixel)            13.066
XM                                      786.403
YM                                       88.147
ZM                                       151.01
BX                                          774
BY                                           76
BZ                                          136
B-width                                      26
B-height                                     25
B-depth                                      32
experiment                       GAERSDIV4_2_3?
Name: 11074, dtype: object

In [194]:
print_stats(gaers)

78 different experiments
12500 detected neurons in total
160.26 neurons per experiment on average

DIV10:
17 experiments
3121 neurons
183.59 neurons per exp

DIV14:
13 experiments
2405 neurons
185.00 neurons per exp

DIV21:
12 experiments
1213 neurons
101.08 neurons per exp

DIV4_:
21 experiments
3833 neurons
182.52 neurons per exp

DIV7_:
15 experiments
1928 neurons
128.53 neurons per exp

In [195]:
print_stats(wistar)

12 different experiments
3131 detected neurons in total
260.92 neurons per experiment on average

DIV10:
4 experiments
895 neurons
223.75 neurons per exp

DIV4_:
4 experiments
906 neurons
226.50 neurons per exp

DIV7_:
4 experiments
1330 neurons
332.50 neurons per exp

In [183]:
gaers_exps = set(gaers.experiment)

In [224]:
get_peak_hist(gaers[gaers.experiment==list(gaers_exps)[0]])

array([ 0,  0,  0,  0, 42,  6,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0, 36,
        6,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [225]:
gaers_hist_dict = {}
for exp in gaers_exps:
    hist = get_peak_hist(gaers, exp=exp)
    gaers_hist_dict[exp] = hist

In [232]:
np.sum([gaers_hist_dict[g] for g in gaers_hist_dict if 'DIV4' in g], axis=1).shape

(21,)

In [ ]:
div4 = 
for g in gaers_hist_dict:
    for d in div:
        
    if 'DIV4' in g:
        print()